import { Component, OnInit } from '@angular/core';
import { Produto, ProdutoService } from '../../services/produto.service';

@Component({
  selector: 'app-produtos',
    templateUrl: './produtos.component.html',
      styleUrls: ['./produtos.component.css'],
      })
      export class ProdutosComponent implements OnInit {
        produtos: Produto[] = [];

          // Formulario de cadastro (CREATE)
            novoProduto: Produto = {
                nome: '',
                    categoria: '',
                        preco: 0,
                            quantidade: 0,
                              };

                                // Produto em edicao (UPDATE), null quando nenhum esta sendo editado
                                  produtoEmEdicao: Produto | null = null;

                                    carregando = false;
                                      mensagemErro = '';
                                        mensagemSucesso = '';

                                          constructor(private produtoService: ProdutoService) {}

                                            ngOnInit(): void {
                                                this.carregarProdutos();
                                                  }

                                                  // ----- READ (GET) -----
                                                    carregarProdutos(): void {
                                                        this.carregando = true;
                                                            this.limparMensagens();
                                                                this.produtoService.listar().subscribe({
                                                                      next: (dados) => {
                                                                              this.produtos = dados;
                                                                                      this.carregando = false;
                                                                                            },
                                                                                                  error: (erro) => {
                                                                                                          this.carregando = false;
                                                                                                                  this.mensagemErro =
                                                                                                                            'Nao foi possivel carregar os produtos. Verifique se a API local esta rodando em ' +
                                                                                                                                      'http://localhost:3000 (erro: ' + (erro?.message || erro) + ').';
                                                                                                                                            },
                                                                                                                                                });
                                                                                                                                                  }
                                                                                                                                                  
                                                                                                                                                    // ----- CREATE (POST) -----
                                                                                                                                                      cadastrarProduto(): void {
                                                                                                                                                          this.limparMensagens();
                                                                                                                                                          
                                                                                                                                                              if (!this.novoProduto.nome || this.novoProduto.preco <= 0) {
                                                                                                                                                                    this.mensagemErro = 'Preencha ao menos o nome e um preco valido para cadastrar o produto.';
                                                                                                                                                                          return;
                                                                                                                                                                              }
                                                                                                                                                                              
                                                                                                                                                                                  this.produtoService.criar(this.novoProduto).subscribe({
                                                                                                                                                                                        next: (produtoCriado) => {
                                                                                                                                                                                                this.produtos.push(produtoCriado);
                                                                                                                                                                                                        this.mensagemSucesso = 'Produto "' + produtoCriado.nome + '" cadastrado com sucesso!';
                                                                                                                                                                                                                this.novoProduto = { nome: '', categoria: '', preco: 0, quantidade: 0 };
                                                                                                                                                                                                                      },
                                                                                                                                                                                                                            error: (erro) => {
                                                                                                                                                                                                                                    this.mensagemErro = 'Erro ao cadastrar produto: ' + (erro?.error?.erro || erro?.message || erro);
                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                // ----- Iniciar edicao (prepara UPDATE) -----
                                                                                                                                                                                                                                                  iniciarEdicao(produto: Produto): void {
                                                                                                                                                                                                                                                      this.limparMensagens();
                                                                                                                                                                                                                                                          this.produtoEmEdicao = { ...produto };
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                              cancelarEdicao(): void {
                                                                                                                                                                                                                                                                  this.produtoEmEdicao = null;
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                      // ----- UPDATE (PUT) -----
                                                                                                                                                                                                                                                                        salvarEdicao(): void {
                                                                                                                                                                                                                                                                            if (!this.produtoEmEdicao || !this.produtoEmEdicao.id) {
                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                          this.limparMensagens();
                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                              const { id, ...dadosAtualizados } = this.produtoEmEdicao;
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                  this.produtoService.atualizar(id as number, dadosAtualizados).subscribe({
                                                                                                                                                                                                                                                                                                        next: (produtoAtualizado) => {
                                                                                                                                                                                                                                                                                                                const indice = this.produtos.findIndex((p) => p.id === produtoAtualizado.id);
                                                                                                                                                                                                                                                                                                                        if (indice !== -1) {
                                                                                                                                                                                                                                                                                                                                  this.produtos[indice] = produtoAtualizado;
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                  this.mensagemSucesso = 'Produto "' + produtoAtualizado.nome + '" atualizado com sucesso!';
                                                                                                                                                                                                                                                                                                                                                          this.produtoEmEdicao = null;
                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                      error: (erro) => {
                                                                                                                                                                                                                                                                                                                                                                              this.mensagemErro = 'Erro ao atualizar produto: ' + (erro?.error?.erro || erro?.message || erro);
                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                          // ----- DELETE (DESTROY) -----
                                                                                                                                                                                                                                                                                                                                                                                            removerProduto(produto: Produto): void {
                                                                                                                                                                                                                                                                                                                                                                                                if (!produto.id) return;
                                                                                                                                                                                                                                                                                                                                                                                                    const confirmar = confirm('Tem certeza que deseja remover "' + produto.nome + '"?');
                                                                                                                                                                                                                                                                                                                                                                                                        if (!confirmar) return;
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                            this.limparMensagens();
                                                                                                                                                                                                                                                                                                                                                                                                                this.produtoService.remover(produto.id).subscribe({
                                                                                                                                                                                                                                                                                                                                                                                                                      next: () => {
                                                                                                                                                                                                                                                                                                                                                                                                                              this.produtos = this.produtos.filter((p) => p.id !== produto.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                      this.mensagemSucesso = 'Produto "' + produto.nome + '" removido com sucesso!';
                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                  error: (erro) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                          this.mensagemErro = 'Erro ao remover produto: ' + (erro?.error?.erro || erro?.message || erro);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        private limparMensagens(): void {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            this.mensagemErro = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                this.mensagemSucesso = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
